version: '3.8'
services:
  backup-pro:
    image: your_dockerhub_username/mail-backup-pro:latest
    container_name: mail-backup
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # 1. 映射宿主机需要备份的目录到容器内
      - /data/docker_data:/data/docker_data
      # 2. 持久化数据库文件
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
